### ISSUE TITLE
Publish a new version on npm with the support of the latest version of leaflet

### ISSUE THREAD

**Issue by SylvainCorlay** [digidem/leaflet-side-by-side#20]
It seems that only the master branch supports leaflet `1.x`.

Would it be possible for you guys to make a new npm release for this patch to be available?

(Just a quick npm version patch & npm install & npm publish would fix this 😏)

**Comment by SylvainCorlay** [comment]
cc @RacingTadpole 

Just a quick `npm install & npm publish` would fix this 😏

**Comment by SylvainCorlay** [comment]
Ping @racingtadpole @gmaclennan

**Comment by SylvainCorlay** [comment]
Following up on this: any chance for leaflet-side-by-side to get an update on npm with the latest fix from master. It just does not allow leaflet 1.x at the moment.

**Comment by gmaclennan** [comment]
ok published `v2.1.0` - FYI you can always replace the version number in package.json with `digidem/leaflet-side-by-side` or even a specific commit `digidem/leaflet-side-by-side#290b448` - useful for when devs like us ignore issues like this for a while :)

**Comment by SylvainCorlay** [comment]
Thanks!
