### ISSUE TITLE
How to remove controller

### ISSUE THREAD

**Issue by robohal** [digidem/leaflet-side-by-side#6]
Doesnt seem like the typical removeFrom(map) is supported for this plugin.  Am i getting it wrong?  If so, could you provide an example?

**Comment by benboughton1** [comment]
sbs = L.control.sideBySide(left,right);
sbs.addTo(mymap)
mymap.removeControl(sbs)

**Comment by gmaclennan** [comment]
Thanks for answering @benboughton1 !

**Comment by karydja** [comment]
@gmaclennan Did this solution work well in your project? I'm still getting the error issue #8 presented :/

**Comment by billyhunt** [comment]
I am also having the same issue.  remove(), removeFrom(map), and removeControl(map) are not working.

**Comment by anjula-sack** [comment]
I  am also having the same issue

**Comment by grwise1** [comment]
Same here
